[FEAT]-Data and Styling to Boardgame Detail [id] Page
idiglove/aintboard pull request #240
Opened 2023-11-25 11:19 UTC by twentymurial33

Done
- [x]  Added Header
- [x]  Added Footer
- [x] Added Card to dynamically get the details info
- [x]  Styling the card 

<img width="612" alt="Screenshot 2023-12-19 at 1 02 08 PM" src="https://github.com/idiglove/aintboard/assets/34128735/d1d82fcd-e114-41eb-9b86-05d9b3535910">

2023-11-27 04:47 UTC, idiglove commented on components/BoardGamePage/BoardGameList.tsx
why do we have changes on this file?

2023-11-27 04:47 UTC, idiglove commented on components/BoardGamePage/BoardGameListWrapper.tsx
also here

2023-11-27 04:48 UTC, idiglove commented on components/Paginate/Paginate.tsx
> +          onClick={(e: React.MouseEvent<HTMLParagraphElement>) => {
not bad

2023-11-27 04:48 UTC, idiglove commented on components/Paginate/Paginate.tsx
> +    // let pages:JSX.Element[] = [];
but we dont need this comment, no?

2023-11-27 04:49 UTC, idiglove commented on pages/boardgames/detail/[id].tsx
> +        description="Explore our comprehensive board game collection, featuring top picks from BoardGameGeek and Ain'tboard rankings. Dive into a world of strategic fun, with games rated and reviewed
let's think of a better description, dont worry about it in this PR. but any suggestions are welcome

2023-11-27 04:49 UTC, idiglove requested changes
i commented here and on discord

2023-11-27 14:06 UTC, twentymurial33 commented on components/Paginate/Paginate.tsx
> +    // let pages:JSX.Element[] = [];
No we don't - removed it

2023-11-27 14:11 UTC, twentymurial33 commented on pages/boardgames/detail/[id].tsx
> +        description="Explore our comprehensive board game collection, featuring top picks from BoardGameGeek and Ain'tboard rankings. Dive into a world of strategic fun, with games rated and reviewed
will do

2023-11-27 14:29 UTC, twentymurial33 commented on components/BoardGamePage/BoardGameList.tsx
That was from the mistake before -reverted the changes

2023-11-27 14:30 UTC, twentymurial33 commented on components/BoardGamePage/BoardGameListWrapper.tsx
That was from the mistake before -reverted the changes

2023-12-09 00:39 UTC, idiglove commented on components/BoardDetailsPage/BoardDescription.tsx
> +import React from "react";
do we still need tis page? if yes, why are we fetching in client side with useSwr?

2023-12-09 00:39 UTC, idiglove commented on components/BoardDetailsPage/BoardDetailsPage.tsx
> +      try {
again we're not doing client side fetching

2023-12-09 00:39 UTC, idiglove commented on components/BoardDetailsPage/CardPage.tsx
> +      const data = queryString.stringifyUrl({
same here

2023-12-09 00:40 UTC, idiglove commented on db/getSpecificBoardgame.ts
> +export async function getSpecificBoardgame(
why is this file here? is this PR updated with develop?

2023-12-09 00:56 UTC, twentymurial33 commented on db/getSpecificBoardgame.ts
> +export async function getSpecificBoardgame(
Yes its updated with `develop` and upto date per the last changes

2023-12-09 01:03 UTC, twentymurial33 commented on components/BoardDetailsPage/BoardDescription.tsx
> +import React from "react";
I'll revert this back - this is the one I got working with useSwr

2023-12-10 01:21 UTC, idiglove commented on pages/boardgames/detail/[id].tsx
> +const BoardgameDetailPage = ({ bgData, bggData }: Props) => {
this is already not aligned to what i said. this should be agnostic means shouldnt know what api it's calling

2023-12-10 01:21 UTC, idiglove commented on pages/boardgames/detail/[id].tsx
>          bgData,
what is diff of bgData and bggData? shouldnt it be just bgData. do all transformation of data here pls

2023-12-10 17:56 UTC, twentymurial33 commented on pages/boardgames/detail/[id].tsx
>          bgData,
ok

2023-12-10 21:55 UTC, idiglove commented on components/BoardDetailsPage/BoardDetailsPage.tsx
> +        const data = queryString.stringifyUrl({
why do we still have it here? i keep saying we are doing server side fetching, not client side fetching anymore

2023-12-10 21:56 UTC, idiglove commented on pages/boardgames/detail/[id].tsx
> +  try {
where's the fetching here? the server side fetching should be here

just look at how i did it on other getServerSideProps in other pages

2023-12-11 05:16 UTC, idiglove commented on components/BoardGamePage/BoardGameList.tsx
> +  const id = Number(1);
what is this id for?

2023-12-11 05:17 UTC, idiglove commented on components/Challenges/ChallengesPage/index.tsx
> +        {lastResponseHasMore ? (
why did u change this page?

2023-12-11 05:17 UTC, idiglove commented on pages/api/img/most-played.tsx
> +  //   console.error("Error fetching the image:", error);
why are there changes here?

2023-12-11 05:18 UTC, idiglove commented on pages/boardgames/detail/[id].tsx
> +      url: `http://127.0.0.1:3002/api/bgg/get-thing`,
u know this url wont work in prod right? our local api wont work here cos its in the same server. unless u use the same domain i think. just use the db functions. easier that way

2023-12-11 05:19 UTC, idiglove commented on pages/boardgames/detail/[id].tsx
> +      parsedData?.items[0].item[0].name?.[0]?.["_attributes"]?.value || "";
this us good

2023-12-11 05:19 UTC, idiglove commented on pages/boardgames/detail/[id].tsx
> +    console.log(jsonData);
but pls remove console logs

2023-12-11 10:32 UTC, twentymurial33 commented on pages/boardgames/detail/[id].tsx
> +    console.log(jsonData);
Removed

2023-12-11 19:19 UTC, twentymurial33 commented on components/Challenges/ChallengesPage/index.tsx
> +        {lastResponseHasMore ? (
It was erroring in prod , but reverted it back

2023-12-11 19:21 UTC, twentymurial33 commented on components/BoardGamePage/BoardGameList.tsx
> +  const id = Number(1);
I didn't add it - but removed it

2023-12-14 20:18 UTC, twentymurial33 commented on pages/boardgames/detail/[id].tsx
> +      url: `http://127.0.0.1:3002/api/bgg/get-thing`,
Updated

2023-12-14 22:35 UTC, idiglove requested changes

2023-12-14 22:35 UTC, idiglove commented on db/getSpecificBoardgame.ts
> +import { ObjectId } from "mongodb";
whats the change on this file? can you update your pr from develop. i don't think this file should be changed

2023-12-19 00:39 UTC, idiglove commented on components/BoardDetailsPage/BoardDetailsPage.tsx
> +  console.log(boardData);
remove console log

2023-12-19 00:48 UTC, idiglove commented on components/BoardDetailsPage/BoardDetailsPage.tsx
> +              {nameValue}| {yearValue}
```suggestion
              {nameValue} | {yearValue}
```

2023-12-19 00:49 UTC, idiglove commented on components/BoardDetailsPage/BoardDetailsPage.tsx
> +          <BoardGameList>{descriptionUrl}</BoardGameList>
BoardGameList but the child is description? i dont understand

2023-12-19 00:51 UTC, idiglove commented on components/BoardDetailsPage/BoardDetailsPage.tsx
> +          <BoardGameList>{descriptionUrl}</BoardGameList>
it should be probably named and let's add Styled in the suffix
something like: *DescriptionStyled*

2023-12-19 00:51 UTC, idiglove commented on components/BoardDetailsPage/BoardDetailsPage.tsx
> +          <Image src={imageUrl} alt={"test"} width={192} height={192} />
```suggestion
          <Image src={imageUrl} alt={can be boardgame name here} width={192} height={192} />
```

2023-12-19 00:52 UTC, idiglove commented on components/BoardDetailsPage/styled.ts
> +  /* background-color: ${(props) => props.theme.colors.lightYellow}; */
whats this commented code?

2023-12-19 00:54 UTC, idiglove commented on db/bg.js
> +    console.log(first);
what i dont understand is why make changes here, when Ive already prepared the fetching before here `db/getSpecificBoardgame.ts`

and db/getSpecificBoardgame.ts -> has join for reviews data

2023-12-19 00:55 UTC, idiglove commented on db/boardGameDetails.js
> +  console.log(url);
remove console log

2023-12-19 00:55 UTC, idiglove commented on db/boardGameDetails.js
> +    console.log(jsonData);
this one too

2023-12-19 00:55 UTC, idiglove commented on db/boardGameDetails.js
> +    console.log(parsedData);
this one too

i suggest searching all console logs in whole codebase, and see if you left them there

2023-12-19 00:55 UTC, twentymurial33 commented on components/BoardDetailsPage/BoardDetailsPage.tsx
> +          <BoardGameList>{descriptionUrl}</BoardGameList>
I'll rename the HTML element

2023-12-19 00:56 UTC, idiglove commented on pages/boardgames/detail/[id].tsx
> +    console.log(imgUrl, yearValue);
this one too

2023-12-19 00:56 UTC, twentymurial33 commented on components/BoardDetailsPage/styled.ts
> +  /* background-color: ${(props) => props.theme.colors.lightYellow}; */
That was for testing - I'll remove all commented code

2023-12-19 00:56 UTC, idiglove commented on pages/boardgames/detail/[id].tsx
> +      nameValue: nameValue,
looks good but why rename the object props? 
```suggestion
    const boardData = {
descUrl,
imgUrl,
yearValue,
nameValue,
```
we can just do this no?

2023-12-19 01:03 UTC, twentymurial33 commented on pages/boardgames/detail/[id].tsx
> +      nameValue: nameValue,
This was breaking before - but I will test again

2023-12-19 01:04 UTC, idiglove commented on pages/boardgames/detail/[id].tsx
> +      nameValue: nameValue,
i guess bcos the one that consumes it doesnt match the data structure

2023-12-19 01:06 UTC, twentymurial33 commented on db/boardGameDetails.js
> +    console.log(parsedData);
done

2023-12-19 16:07 UTC, twentymurial33 commented on pages/boardgames/detail/[id].tsx
> +      nameValue: nameValue,
Yes - I will leave it as is because when I change it the client side breaks

2023-12-19 18:13 UTC, twentymurial33 commented on db/bg.js
> +    console.log(first);
I wanted to setup my own functions in the persistance layer so I can fully understand the codebase

2023-12-19 18:15 UTC, idiglove commented on db/bg.js
> +    console.log(first);
Understood. But pls use `db/getSpecificBoardgame.ts` this one instead. It has join for reviews, because I want to show linked reviews on this page later on

2023-12-19 22:26 UTC, idiglove commented on db/bg.js
> +    console.log(first);
look at this pls @twentymurial33

2023-12-19 23:26 UTC, twentymurial33 commented on db/bg.js
> +    console.log(first);
ok

2023-12-20 18:33 UTC, idiglove approved these changes
lgtm

2023-12-20 18:33 UTC, merged