[AMP-18] Edit a review/strategy as a user
idiglove/aintboard pull request #280
Opened 2023-12-26 17:55 UTC by twentymurial33

1. User is able to edit contents of the review card and navigate back to `details` and `listing` page to see the changes 

<img width="654" alt="Screenshot 2024-01-17 at 11 57 37 AM" src="https://github.com/idiglove/aintboard/assets/34128735/d0da9510-0c62-4842-875c-575f2ceddbbe">

<img width="474" alt="Screenshot 2024-01-17 at 11 57 59 AM" src="https://github.com/idiglove/aintboard/assets/34128735/04a1098b-1090-4656-97c6-c43fd950867b">

2024-01-09 01:40 UTC, idiglove commented on pages/review/[slug].tsx
> +const Slug = ({ reviewData, updateReviewCard }: Props) => {
what is `updateReviewCard`? is it a function or a data?

2024-01-09 15:19 UTC, twentymurial33 commented on pages/review/[slug].tsx
> +const Slug = ({ reviewData, updateReviewCard }: Props) => {
Its a function that I'm passing down as a prop

2024-01-10 20:12 UTC, idiglove commented on components/Reviews/EditReview/index.tsx
> +const EditReviewForm: React.FC<EditSimpleFormProps & { id: string }> = ({
Now thinking about it. You can SSR this. That way you can get all data from server side along with the id from context param

2024-01-10 20:12 UTC, idiglove commented on components/Reviews/EditReviewContent/NewEditTemplate/index.tsx
> +const NewReviewTemplate: React.FC<NewReviewTemplateProps & { id: string }> = ({
```suggestion
const EditReviewTemplate: React.FC<EditReviewTemplateProps & { id: string }> = ({
```

also if you want to add the id as prop just add it to EditReviewTemplateProps

2024-01-10 20:13 UTC, idiglove commented on pages/review/edit/[slug].tsx
> +    const id = context?.params?.id;
ahh. thats why you dont get the id because your file structure is [slug].tsx

so it should be context?.params?.slug

2024-01-10 21:48 UTC, twentymurial33 commented on pages/review/edit/[slug].tsx
> +    const id = context?.params?.id;
updated

2024-01-10 22:10 UTC, twentymurial33 commented on components/Reviews/EditReviewContent/NewEditTemplate/index.tsx
> +const NewReviewTemplate: React.FC<NewReviewTemplateProps & { id: string }> = ({
I'm confused I already had it this way

2024-01-12 22:44 UTC, idiglove requested changes

2024-01-12 22:44 UTC, idiglove commented on components/Reviews/EditReview/index.tsx
> +    { setSubmitting, resetForm }: any
if we can, lets not use any. if we dont usually do it before, then lets keep it this way

2024-01-12 22:44 UTC, idiglove commented on components/Reviews/EditReview/index.tsx
> +      console.log(values);
remove console log

2024-01-12 22:44 UTC, idiglove commented on components/Reviews/EditReviewContent/NewEditTemplate/index.tsx
> +//import EditStrategy from "components/Reviews/EditStrategy";
remove unused imports

2024-01-12 22:44 UTC, idiglove commented on components/Reviews/EditReviewContent/NewEditTemplate/index.tsx
> +import { setReviewType } from "redux/slices/reviewFormSlice";
not sure why we need redux for this. we used redux on new templates, because we can switch from Review type or Strategy type. Pls review this usage if it's really necessary

2024-01-12 22:44 UTC, idiglove commented on components/Reviews/EditReviewContent/NewEditTemplate/index.tsx
> +      {/* <EditStrategy initialValues={initialValues}/> */}
remove pls

2024-01-12 22:44 UTC, idiglove commented on components/Reviews/EditReviewContent/index.tsx
> +  console.log(reviewData);
remove console log

2024-01-12 22:44 UTC, idiglove commented on components/Reviews/EditReviewContent/index.tsx
> +        updateReviewCard={updateReviewCard}
lets do naming like `handleUpdate..` or `onUpdate...`

2024-01-12 22:44 UTC, idiglove commented on components/Reviews/EditStrategy/index.tsx
> +      console.log(response.data);
remove console log

2024-01-12 22:44 UTC, idiglove commented on components/Reviews/EditStrategy/index.tsx
> +      {({ isSubmitting }) => (
lets focus on review template first. it will be easier to work on this once review is done

2024-01-12 22:44 UTC, idiglove commented on components/Reviews/ReviewArticlePage/index.tsx
> +  useEffect(() => {
why do we need a useEffect here?

2024-01-12 22:44 UTC, idiglove commented on components/Reviews/ReviewArticlePage/index.tsx
> +  useEffect(() => {
if you want to update this page from its edited data, theres another strategy. dont worry about it now

2024-01-12 22:44 UTC, idiglove commented on components/Reviews/ReviewArticlePage/index.tsx
> +  useEffect(() => {
for testing purposes, rely on db changes for now

2024-01-12 22:44 UTC, idiglove commented on db/reviews.js
> +    console.log("New values:", { title, language, youtubeUrl });
remove console log

2024-01-12 22:44 UTC, idiglove commented on db/reviews.js
> +      .updateOne({ _id: id }, { $set: { title, language, youtubeUrl } });
the set options should be changed accordingly once you work more on this

2024-01-12 22:44 UTC, idiglove commented on pages/api/review/edit/[id].js
> +    console.log(updatedReview);
another console log. lets keep it clean of console logs pls. do you know why we need to remove them?

2024-01-12 22:44 UTC, idiglove commented on pages/review/edit.tsx
> +//         isHomepage={false}
remove if unnecessary

2024-01-12 22:44 UTC, idiglove commented on pages/review/edit.tsx
> +import EditReviewContent from "components/Reviews/EditReviewContent";
i dont think we need this page anymore

2024-01-12 22:44 UTC, idiglove commented on pages/review/edit/[slug].tsx
> +    };
where is the fetching of data?

2024-01-14 01:16 UTC, twentymurial33 commented on pages/review/edit.tsx
> +import EditReviewContent from "components/Reviews/EditReviewContent";
Yes removed it

2024-01-14 01:25 UTC, twentymurial33 commented on components/Reviews/EditReviewContent/NewEditTemplate/index.tsx
> +      {/* <EditStrategy initialValues={initialValues}/> */}
removed

2024-01-14 01:26 UTC, twentymurial33 commented on components/Reviews/EditReview/index.tsx
> +      console.log(values);
removed

2024-01-15 23:31 UTC, twentymurial33 commented on components/Reviews/EditReviewContent/NewEditTemplate/index.tsx
> +import { setReviewType } from "redux/slices/reviewFormSlice";
Removed it.

2024-01-17 17:44 UTC, idiglove commented on pages/review/edit/[slug].tsx
> +const Slug = ({ reviewData, id }: Props) => {
lets name this component EditReviewPage

2024-01-24 16:07 UTC, idiglove commented on components/Reviews/EditReviewContent/index.tsx
> +  console.log(reviewData);
it still here

2024-01-24 16:08 UTC, idiglove commented on db/reviews.js
> +        { $set: { title, language, youtubeUrl, content, overalRating } }
```suggestion
        { $set: { title, language, youtubeUrl, content, overallRating } }
```

2024-01-24 16:08 UTC, idiglove commented on pages/api/review/edit/[slug].js
> +  console.log(review);
remove console log

2024-01-24 16:08 UTC, idiglove commented on pages/review/[slug].tsx
> +  console.log(updateReviewCard);
remove console log

2024-01-24 19:05 UTC, twentymurial33 commented on pages/review/[slug].tsx
> +  console.log(updateReviewCard);
removed

2024-01-24 19:06 UTC, twentymurial33 commented on pages/api/review/edit/[slug].js
> +  console.log(review);
removed

2024-01-24 20:11 UTC, twentymurial33 commented on db/reviews.js
> +        { $set: { title, language, youtubeUrl, content, overalRating } }
Updated directly to local and will push

2024-01-29 20:51 UTC, idiglove requested changes
nice job! i just have some comments, and i will do some testing soon

2024-01-29 20:51 UTC, idiglove commented on components/Reviews/EditReview/index.tsx
> +    console.log(sum);
remove console logs pls

2024-01-29 20:51 UTC, idiglove commented on components/Reviews/EditReview/index.tsx
> +      router.push(`/review/${slug}?overallRating=${overallRatingVal}`);
why are there 2 router push?

2024-01-29 20:51 UTC, idiglove commented on components/Reviews/EditReviewContent/EditTemplate/index.tsx
> +import { NewReviewTemplateWrapper, Title } from "../../NewReviewContent/styled";
use relative imports. Lets not use `../../`

2024-01-29 20:51 UTC, idiglove commented on components/Reviews/ReviewArticlePage/index.tsx
> +import { AuthContext } from "../../../context/AuthProvider";
lets not use ../../ for imports

2024-01-29 20:51 UTC, idiglove commented on components/Reviews/ReviewArticlePage/index.tsx
> +            <>{/* <ReactPlayer url={review.youtubeUrl} width="40rem" /> */}</>
why are we removing this?

2024-01-29 20:51 UTC, idiglove commented on components/Reviews/ReviewForm/index.tsx
> +                  overallRating={overallRating}
why do we have this now? do we need to update this file?

2024-01-29 20:51 UTC, idiglove commented on db/reviews.js
> +  }
no need to destructure

2024-01-29 20:51 UTC, idiglove commented on db/reviews.js
> +        },
then just put value here
{...values}

2024-01-29 20:51 UTC, idiglove commented on pages/api/review/edit/[slug].js
> +    overalRating,
same no need to destructure

2024-01-29 20:51 UTC, idiglove commented on pages/review/[slug].tsx
> +import { ReviewData, ReviewApiResponse } from "../../types/types";
lets not use ../../ as imports

2024-01-29 20:51 UTC, idiglove commented on pages/review/edit/[slug].tsx
> +
lets fix imports

2024-01-29 20:51 UTC, idiglove commented on pages/review/edit/[slug].tsx
> +    console.log(review);
remove console log pls.
the trick to find these console logs is look  at this page in github and ctrl +f an look for "console.log"

2024-01-29 20:51 UTC, idiglove commented on pages/review/edit/[slug].tsx
> +          componentsRating: review.componentsRating,
no need to destructure just do {...review}

2024-02-02 19:46 UTC, twentymurial33 commented on components/Reviews/ReviewArticlePage/index.tsx
> +            <>{/* <ReactPlayer url={review.youtubeUrl} width="40rem" /> */}</>
we are not - I will return it back

2024-02-02 20:06 UTC, twentymurial33 commented on pages/review/[slug].tsx
> +import { ReviewData, ReviewApiResponse } from "../../types/types";
Updated

2024-02-02 20:07 UTC, twentymurial33 commented on pages/review/edit/[slug].tsx
> +
done

2024-02-02 22:10 UTC, twentymurial33 commented on components/Reviews/ReviewArticlePage/index.tsx
> +import { AuthContext } from "../../../context/AuthProvider";
updated

2024-02-02 22:40 UTC, twentymurial33 commented on components/Reviews/EditReviewContent/EditTemplate/index.tsx
> +import { NewReviewTemplateWrapper, Title } from "../../NewReviewContent/styled";
updated

2024-02-02 22:55 UTC, twentymurial33 commented on components/Reviews/EditReview/index.tsx
> +      router.push(`/review/${slug}?overallRating=${overallRatingVal}`);
updated

2024-02-03 00:17 UTC, twentymurial33 commented on pages/api/review/edit/[slug].js
> +    overalRating,
?

2024-02-03 03:53 UTC, idiglove requested changes
Will message you in discord

2024-02-03 03:53 UTC, idiglove commented on components/Common/DropDown/index.tsx
> +import React, { useEffect, useState, useMemo } from "react";
we dont need to import React here

2024-02-03 03:53 UTC, idiglove commented on components/Common/DropDown/index.tsx
>      }
why are we changing this common dropdown? would there be any regression in other parts? would need to get a good reason why we're doing this

2024-02-03 03:53 UTC, idiglove commented on components/Reviews/EditReview/index.tsx
> +    console.log(sum);
remove console log

2024-02-03 03:53 UTC, idiglove commented on components/Reviews/EditReview/index.tsx
> +
what is this for?

2024-02-03 03:53 UTC, idiglove commented on components/Reviews/EditReview/index.tsx
> +                console.log("Selected option:", selectedOption);
remove console log

2024-02-03 03:53 UTC, idiglove commented on components/Reviews/EditReviewContent/EditTemplate/index.tsx
> +//   review,
do we need these comments?

2024-02-03 03:53 UTC, idiglove commented on pages/api/review/edit/[slug].js
> +    youtubeUrl,
const values = req.body


then ...editReview(req.db, values)

^ instead of destructuring everything

2024-02-03 03:53 UTC, idiglove commented on pages/review/edit/[slug].tsx
> +      },
what is diff of reviewData from initialValues?

2024-02-03 14:46 UTC, twentymurial33 commented on components/Reviews/EditReviewContent/EditTemplate/index.tsx
> +//   review,
No - I totally forgot to remove these

2024-02-03 15:20 UTC, twentymurial33 commented on components/Reviews/EditReview/index.tsx
> +
we don't need them - it was me validating and testing - I need to make sure i form a habit of removing all my tests and console.logs

2024-02-03 15:33 UTC, twentymurial33 commented on components/Common/DropDown/index.tsx
> +import React, { useEffect, useState, useMemo } from "react";
updated

2024-02-03 15:43 UTC, twentymurial33 commented on pages/api/review/edit/[slug].js
> +    youtubeUrl,
thank you - updated

2024-02-03 15:46 UTC, twentymurial33 commented on components/Common/DropDown/index.tsx
>      }
Ok - we will chat more during reviewing the flows

2024-02-03 15:46 UTC, twentymurial33 commented on pages/api/review/edit/[slug].js
> +    overalRating,
updated per later comment

2024-02-03 15:50 UTC, twentymurial33 commented on components/Reviews/EditReview/index.tsx
> +    console.log(sum);
done

2024-02-05 16:20 UTC, idiglove requested changes

2024-02-05 16:20 UTC, idiglove commented on pages/review/[slug].tsx
> +    updateReviewCard(updatedReview, values);
what does this function do? why do we have this in `pages` level?

2024-02-05 16:20 UTC, idiglove commented on pages/review/edit/[slug].tsx
> +      },
this is not resolved yet

2024-02-05 20:44 UTC, twentymurial33 commented on pages/review/[slug].tsx
> +    updateReviewCard(updatedReview, values);
removed the function and passed it directly

2024-02-05 22:07 UTC, twentymurial33 commented on pages/review/edit/[slug].tsx
> +      },
removed `reviewData`

2024-02-06 17:30 UTC, idiglove requested changes

2024-02-06 17:30 UTC, idiglove commented on components/Challenges/CreateChallengeForm/index.tsx
> +        <Field as={Form}>
why are we changing this file?

2024-02-06 17:30 UTC, idiglove commented on components/Common/DropDown/index.tsx
> +      } else {
u still havent explained to me why we changed this file

2024-02-06 17:30 UTC, idiglove commented on components/JoinUsForm/index.tsx
> +        <Field as={Form}>
why are we changing this file

2024-02-06 17:30 UTC, idiglove commented on components/OnlineBattle/OnlineBattleForm/index.tsx
> +        <Field as={Form}>
same here

2024-02-06 17:30 UTC, idiglove commented on components/OnlineBattle/SubmitEntryForm/index.tsx
> +        <Field as={Form}>
same here. ok seems like we've done it in multiple areas. pls revert as this is not needed

2024-02-06 17:30 UTC, idiglove commented on components/Reviews/EditReview/index.tsx
> +  }, [initialValues]);
we already set initivalues in lines 55 and 56. why we need to set again on useEffect from 60? I'm really curious, maybe I'm missing some info

2024-02-06 17:30 UTC, idiglove commented on components/Reviews/EditReview/index.tsx
> +          <Field as={Form}>
why are we doing Field as Form? we've never done this before

2024-02-06 17:30 UTC, idiglove commented on components/Reviews/EditStrategy/index.tsx
> +  const dispatch = useDispatch();
oh so you also did EditStrategy? thats good 😊

2024-02-06 17:30 UTC, idiglove commented on components/Reviews/ReviewForm/index.tsx
> +          <Field as={Form}>
pls check

2024-02-06 17:30 UTC, idiglove commented on components/Reviews/ReviewForm/index.tsx
> +                  overallRating={overallRating}
pls check this one

2024-02-06 17:30 UTC, idiglove commented on db/reviews.js
> +        },
this is still not resolved

2024-02-06 17:48 UTC, twentymurial33 commented on components/Reviews/EditReview/index.tsx
> +          <Field as={Form}>
This was from the build error from `Next.js` and per the documentation this is the proposed solution and YES it will be the 1st time we implement it

2024-02-06 17:48 UTC, twentymurial33 commented on components/Reviews/EditStrategy/index.tsx
> +  const dispatch = useDispatch();
Yes

2024-02-06 17:49 UTC, twentymurial33 commented on components/Reviews/ReviewForm/index.tsx
> +          <Field as={Form}>
This was from the build error from `Next.js` and per the documentation this is the proposed solution and YES it will be the 1st time we implement it

2024-02-06 17:55 UTC, idiglove commented on components/Reviews/ReviewForm/index.tsx
> +          <Field as={Form}>
i never encountered this error. can you show the link to that doc pls?

2024-02-06 23:14 UTC, twentymurial33 commented on components/Common/DropDown/index.tsx
> +      } else {
we had a `getValue` function that was introducing a maintenance point for `emptyDefault` which was what I was solving for by using `useEffect`

2024-02-06 23:17 UTC, twentymurial33 commented on components/Reviews/ReviewForm/index.tsx
> +                  overallRating={overallRating}
nothing changed here.

2024-02-19 05:52 UTC, idiglove approved these changes

2024-02-19 05:58 UTC, merged