[AB-21] FE: Header component
idiglove/aintboard pull request #296
Opened 2024-01-26 01:46 UTC by twentymurial33

**Acceptance Criteria**

- BGU should see a new header design based on Figma
- Should follow all responsive screens
- Navbar still exists and has the same functionality
- This component is a dumb/presentational component and stateless

Current State 
<img width="1339" alt="Screenshot 2024-01-28 at 3 41 04 PM" src="https://github.com/idiglove/aintboard/assets/34128735/66dd6743-90c5-4717-b5cd-9bab801363de">

2024-01-26 21:02 UTC, idiglove commented on components/CmsHeader/index.tsx
> +
good start! proud of you!

can we have a convention of when using styled components we suffix it with Styled?
bcos i get confused if its a styled comp or a react comp :D

2024-01-26 21:03 UTC, idiglove commented on components/CmsHeader/styled.ts
> +  width: 198px;
these are very arbitrary numbers. we should revisit this. i will create a design system for Links and Buttons. so ignore for now

2024-01-26 21:04 UTC, idiglove commented on components/Header/styled.ts
> +export const Rubikcms = styled.h1`
didnt know this was an h1.
you can say HeadingStyled

2024-01-27 16:48 UTC, twentymurial33 commented on components/CmsHeader/styled.ts
> +  width: 198px;
ok

2024-01-27 17:00 UTC, twentymurial33 commented on components/Header/styled.ts
> +export const Rubikcms = styled.h1`
renamed it to `CmsStyledHeader`

2024-01-27 17:56 UTC, idiglove commented on components/Header/styled.ts
lets make the convention as Styled as suffix
so it will be CMSHeaderStyled

2024-01-30 16:46 UTC, idiglove requested changes
good work. will have to run and test

2024-01-30 16:46 UTC, idiglove commented on assets/img/CMSALPACA.svg
lets remove this file

2024-01-30 16:46 UTC, idiglove commented on components/CmsHeader/index.tsx
> +} from "./styled";
very nice. pls comment on mine too if i forget to do this convention :)

2024-01-30 16:46 UTC, idiglove commented on components/CmsHeader/index.tsx
> +import arrowIcon from "../../assets/img/arrow.svg";
pls make a react component out of it, and it import it as tsx
just like assets/img/AlpacaAvatar.js

2024-01-30 16:46 UTC, idiglove commented on components/CmsHeader/index.tsx
> +            />
no need to use image component, refer to my comment above and use it as a react component

2024-01-30 16:46 UTC, idiglove commented on components/CmsHeader/styled.ts
> +  padding: 238px 41px 340px 42px;
very arbitrary numbers, will check

2024-01-30 16:57 UTC, idiglove reviewed
HeaderContainerStyled should have a padding around it. 
Lets not put outer spacing on breadcrumbs or headers. Let the Container handle the outer padding

2024-01-30 16:57 UTC, idiglove commented on components/CmsHeader/styled.ts
> +  padding: 238px 41px 340px 42px;
oh ok this is the featured image, pls ignore

2024-02-01 13:56 UTC, twentymurial33 commented on components/CmsHeader/index.tsx
> +} from "./styled";
Thank you

2024-02-01 23:18 UTC, twentymurial33 commented on components/CmsHeader/index.tsx
> +            />
In a later comment you told me to leave it - so wasn't sure

2024-02-01 23:36 UTC, idiglove commented on components/CmsHeader/index.tsx
> +            />
oh is it, im going nuts XD But lets fix it here. Icons ideally should be svgs. I will check this PR now and test

2024-02-02 03:02 UTC, idiglove approved these changes
just make the changes i said on discord.
I'll approve this now, and just merge it when youre ready

Dont forget to remove your /pages/cms file

2024-02-02 10:40 UTC, merged