[AR-24] reviews homepage redesign in desktop
idiglove/aintboard pull request #353
Opened 2024-03-08 07:20 UTC by AjGuintu

2024-03-09 01:55 UTC, idiglove requested changes
Nice for putting it out. Just some things to be fixed:
- remove unusued comments
- address my comments
- i will need to test it locally, and i might come back with more comments :)

2024-03-09 01:55 UTC, idiglove commented on components/Avatar/styled.ts
> +      ? "0rem auto 0"
can we just remove the checking for margin altogether for REVIEWS_HOMEPAGE_COMPONENT?

2024-03-09 01:55 UTC, idiglove commented on components/Common/RatingForm/styled.ts
> +  padding: 0;
this is dangerous. Did you check how it will appear where this is used in other parts of the site?

2024-03-09 01:55 UTC, idiglove commented on components/Reviews/ReviewCardV2/BottomPart.tsx
> +// import Image from "next/image";
remove unused import

2024-03-09 01:55 UTC, idiglove commented on components/Reviews/ReviewCardV2/MiddlePart.tsx
> +// import { capitalize } from "lodash";
remove unused import

2024-03-09 01:55 UTC, idiglove commented on components/Reviews/ReviewCardV2/MiddlePart.tsx
> +
remove comments

2024-03-09 01:55 UTC, idiglove commented on components/Reviews/ReviewCardV2/ReviewContent.tsx
> +// import { REVIEWS_HOMEPAGE_COMPONENT } from "util/constants";
remove comments

2024-03-09 01:55 UTC, idiglove commented on components/Reviews/ReviewHomepage/index.tsx
> +import Link from "next/link";
put package import above. custom file imports should be below it

2024-03-09 01:55 UTC, idiglove commented on components/Reviews/ReviewHomepage/styled.ts
> +  max-width: 73rem rem;
this is a syntax error. i think it should only be 73rem;

2024-03-15 16:48 UTC, idiglove requested changes
Hi AJ, good effort, you're becoming more independent now :) 
Few things
- Please care about regression, see if the codes implemented will break existing design or functionality
- Resolve convos in Github PR if done
- Remove unused comments in your codes

I have yet to test this. I will test and leave more comments afterwards

2024-03-15 16:48 UTC, idiglove commented on components/Avatar/styled.ts
> +  margin: 0 auto 0;
can you check if we still need this?
`: props.from === SIDEBAR_COMPONENT || props.noMargin`

2024-03-15 16:48 UTC, idiglove commented on components/Common/OverallRating/index.tsx
> +  className,
nice usage of extending a component!

2024-03-15 16:48 UTC, idiglove commented on components/Common/RatingForm/styled.ts
> +  padding: 0;
Did you check this? @AjGuintu

2024-03-15 16:48 UTC, idiglove commented on components/Header/styled.ts
hmm, wont the homepage be affected by this codes?

2024-03-15 16:48 UTC, idiglove commented on components/Header/styled.ts
> +        left: 7rem;
are we doing this because of the new implementation of Reviews Homepage?

2024-03-15 16:48 UTC, idiglove commented on components/Reviews/ReviewCardV2/BottomPart.tsx
> +// import Image from "next/image";
@AjGuintu

2024-03-15 16:48 UTC, idiglove commented on components/Reviews/ReviewCardV2/ReviewContent.tsx
> +            <Image alt="boardgame" src={data.images[0]} layout="fill" />
pls do `data?.images?[0]` for better error handling

2024-03-15 16:48 UTC, idiglove commented on pages/index.tsx
> +// import FeaturedReviews from "components/FeaturedReviews/FeaturedReviews";
what are these comments for?

2024-03-15 16:54 UTC, idiglove commented
After testing:
I still see that the 
1. title lines are not vertically aligned - everything else on desktop, looks great!
![image](https://github.com/idiglove/aintboard/assets/29911508/a2f404b4-5d0c-417a-96a3-3f8b5bb50796)


2. on 656px screen width
![image](https://github.com/idiglove/aintboard/assets/29911508/cd7bc2be-5e81-457b-8937-5cc7f99f6aee)


The bottom reviews are cut off

Overall, they are well done, I think you just need to address these stuff, and you'll be good :)

2024-03-18 03:12 UTC, AjGuintu commented on components/Header/styled.ts
> +        left: 7rem;
yes :))

2024-03-18 15:45 UTC, idiglove commented on components/Reviews/ReviewCardV2/ReviewContent.tsx
> +            <Image alt="boardgame" src={data.images[0]} layout="fill" />
@AjGuintu

2024-03-19 05:57 UTC, idiglove approved these changes
Make the changes needed, push, then you can merge it

2024-03-19 13:16 UTC, closed without merging