[AT-27] FE: Tournament Registration Form
idiglove/aintboard pull request #368
Opened 2024-03-23 03:36 UTC by Idan-Garay

Requesting feedback on:
- Tournament User Register form
- Data flow of tournamentId to tournament Form
- still using page router
- _document.js and _app.tsx

2024-03-23 04:09 UTC, idiglove requested changes
Nice job! Few things
1. We need to clean up this PR - too many comments
2. The PR title should be be [AT-27] instead of feat/at 27
3. I was able to use the App Router - check my discord msg

Good job on figuring out the mongodb functions :) 🏄🏽

2024-03-23 05:16 UTC, idiglove reviewed
some more feedback

2024-03-23 05:16 UTC, idiglove commented on components/Tournament/RegisterForm/index.tsx
> +    randomQuestion: Yup.string().min(5, "It is too short.").optional(),
this is optional so let's not put a minimum requirement here :)

2024-03-23 05:16 UTC, idiglove commented on components/Tournament/RegisterForm/index.tsx
> +        {
the message should be changed

2024-03-23 05:16 UTC, idiglove commented on db/tournament_users.js
> +    return getFailedResponse(err, "db/tournament_users.js");
do something like this instead
```
return getFailedResponse(
      err?.message ?? "",
      "db/getChallengeCount.ts",
      "Can't get challenge count"
    );
    ```
for more detailed error msg

2024-03-25 15:11 UTC, idiglove reviewed
I like the initiatives, but I dont know if they are needed. I just had a skim thru and would need to check thoroughly. I have added some comments tho. Thanks!☀️

2024-03-25 15:11 UTC, idiglove commented on app/middlewares/database.js
oops what is the reason of these changes on middleware?

2024-03-25 15:11 UTC, idiglove commented on app/tournaments/@modal/default.tsx
interesting. ive not seen a folder prefixed with @. care to share what it is for?

2024-03-25 15:11 UTC, idiglove commented on package.json
> +    "@next-auth/mongodb-adapter": "^1.1.3",
hmm we may have to speak about this. essentially we should use dbForFrontend and server actions. u can check in my video :)

2024-03-26 12:21 UTC, Idan-Garay commented on app/tournaments/@modal/default.tsx
This is for the modal routing in nextjs which utilizes parallel routes (@) and intercepting routes (.).  Parallel routes allows you to navigate a subpage/s without conditional ifs statements in the parent page i.e. a settings page with Tab groups. Rendering a subpage /settings/profile is done through `if (pathname == 'settings/profile') return <ProfilePage/>` but with parellel routes, the subpage `<ProfilePage/>` will be rendered inside the settings page through a file structure` /settings/@nested/profile/pages.tsx`.

As for Interceptor Routes, it can load a route outside the directory scope of a page's layout.tsx. This is used to add a `<Modal>` Component as a parent to `<TournamentRegisterPage/>`, so when users click a tournament's register button, The `<TournamentRegisterPage/>` will be rendered as a page within a Modal, however it will be as a page for shareable link use-case or when the page is refreshed.

References: 
https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#modals
https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes

2024-03-26 12:24 UTC, Idan-Garay commented on app/tournaments/@modal/default.tsx
On a second thought, I haven't mastered this to the point of simplicity so I might use the simpler approach provided in notion (https://medium.com/@dtulpa16/next-js-modals-made-easy-7bdce15b2a5e). I might have `/tournaments?id=1&show=true` as url.

2024-03-26 12:27 UTC, Idan-Garay commented on package.json
> +    "@next-auth/mongodb-adapter": "^1.1.3",
Okay, I'll review for this

2024-03-26 12:54 UTC, Idan-Garay commented on app/middlewares/database.js
The change in middleware was from nc() to createEdgeRouter(). The app router requires api route files to export async function POST() instead of pages router's handler.post(). Otherwise, router.use(all).post(async (req,ctx) => {...}) will result to '405 Method Not Allowed'.

2024-03-27 03:55 UTC, closed without merging