[ASEO-38] FE: Best Games - Comment Section
idiglove/aintboard pull request #420
Opened 2024-05-02 10:18 UTC by Idan-Garay

Acceptance Criteria:

- Static Data
- Layout SectionWithComments Props:
    - HeadingProps
    - SubHeadingProps

2024-05-02 14:34 UTC, idiglove commented on app/_components/Content/ArticleTemplate/index.tsx
> +          title="25 Best Games for Gamenight for Any Occasion"
pls get these prop values from parent

Content components only should consume props. no hardcoded values 

thanks!

2024-05-02 14:36 UTC, idiglove commented on app/_components/Content/CommentItem/index.tsx
> +        <span className="block font-Rubik-Bold text-base tracking-wide">
if using specific colors and fonts here then make sure they are overridable from parent

2024-05-02 14:37 UTC, idiglove commented on app/_components/Layouts/SectionWithComments/README.md
> +First introduced in Tournaments landing page (V4 Figma)
i think your description is inaccurate. 

This was introduced in Best games, no?

also can u add a preview screenshot of this component. 

Trying to understand why we have another Section Layout component

2024-05-02 14:38 UTC, idiglove commented on app/_components/Layouts/SectionWithComments/index.tsx
> +        className={cn(
the html structure looks like another Section that we have. can u check if we can reuse others instead?

2024-05-02 14:39 UTC, idiglove commented on app/layout.tsx
> +      <body className="bg-dark text-white">
hmm i prefer this styles to be in your parent element in your page

2024-05-02 14:40 UTC, idiglove requested changes
some changes needed. Really good effort!

2024-05-03 02:11 UTC, Idan-Garay commented on app/_components/Content/ArticleTemplate/index.tsx
> +          title="25 Best Games for Gamenight for Any Occasion"
commit: fix: add props to Article Template

2024-05-03 02:13 UTC, Idan-Garay commented on app/_components/Content/CommentItem/index.tsx
> +        <span className="block font-Rubik-Bold text-base tracking-wide">
commit fix: add overrideable className for colors and fonts"

2024-05-03 02:29 UTC, Idan-Garay commented on app/_components/Layouts/SectionWithComments/README.md
> +First introduced in Tournaments landing page (V4 Figma)
commit fix: update SectionWithComments component

This is a section layout for maintainability purposes. This will allow other devs to use this section for comments. Finally, react createPortal might be used to render this section to another part of the DOM (refer to mobile version of this page)

<img width="702" alt="image" src="https://github.com/idiglove/aintboard/assets/47768819/79fbe6bb-d3a4-437c-8fda-8e2605a95877">

2024-05-03 02:33 UTC, Idan-Garay commented on app/_components/Layouts/SectionWithComments/index.tsx
> +        className={cn(
This might be affected with the above comment's commit

2024-05-03 02:37 UTC, Idan-Garay commented on app/layout.tsx
> +      <body className="bg-dark text-white">
commit fix: remove tailwindcss className from root layout

2024-05-03 02:38 UTC, Idan-Garay commented
> some changes needed. Really good effort!

Thanks. I've made some changes according your review. @idiglove

2024-05-03 03:48 UTC, idiglove approved these changes
Good job! Make the changes I have said, and this will be good to go :)

2024-05-04 02:27 UTC, idiglove approved these changes
i will merge for now, and we can revisit later

2024-05-04 02:27 UTC, merged