[AT-67] Add Send invitation email after registering
idiglove/aintboard pull request #460
Opened 2024-05-29 01:41 UTC by Idan-Garay

Pre-requisite:
- update environment variables

Testing steps:

1. Visit http://localhost:3002/boardgame-tournaments/the-castles-of-burgundy/2024-05-25
2. Click Register button
3. Fill the form and submit
4. On submit failed, access mongodb compass and delete the row with your email in tournamentUsers Collection i.e. filter {email: "<your_email>"} -> then repeat step 2 & 3
5. On Success, Registration email is sent to the user's email.

2024-05-29 03:19 UTC, idiglove requested changes
some comments

2024-05-29 03:19 UTC, idiglove commented on db/tournamentUsers.ts
> -    }
this is needed, why is this removed?

2024-05-29 03:19 UTC, idiglove commented on util/email/sendRegisterTournamentEmail.ts
> +        templateId: parseInt(BREVO_TOURNAMENT_REGISTER_TEMPLATE_ID ?? "15"),
i prefer to not send a brevo email at all if template is not there

2024-05-29 03:19 UTC, idiglove commented on util/email/sendRegisterTournamentEmail.ts
> +        templateId: parseInt(BREVO_TOURNAMENT_REGISTER_TEMPLATE_ID ?? "15"),
templateId should also be a prop of this function

2024-05-29 03:19 UTC, idiglove commented on app/boardgame-tournaments/_components/FeaturedBoardgameTournaments/index.tsx
> +                    );
whats the reason for changing this?

2024-05-29 03:19 UTC, idiglove commented on app/boardgame-tournaments/_components/FeaturedBoardgameTournaments/index.tsx
> +    link = `/boardgame-tournaments/register?bgName=${featuredGame?.title}&date=${featuredGame?.slug}&tourneyId=${featuredGame?.databaseId}&slug=${featuredGame.uri}`;
we dont need this. We actually need a new ACF field (which i havent taught u) - its ok ill do it and lets remove slug query param from here

2024-05-29 03:25 UTC, Idan-Garay commented on db/tournamentUsers.ts
> -    }
I thought this will prevent user to register in other tournaments if the user is already registered to one. I'll put it back again since there's a brevoListId

2024-05-29 03:28 UTC, Idan-Garay commented on util/email/sendRegisterTournamentEmail.ts
> +        templateId: parseInt(BREVO_TOURNAMENT_REGISTER_TEMPLATE_ID ?? "15"),
Making it as a prop requires prefixing it with NEXT_PUBLIC to be usable in client component since the components where it's used has "use client" and passed as props. Should I make it as a prop?

2024-05-29 03:31 UTC, Idan-Garay commented on app/boardgame-tournaments/_components/FeaturedBoardgameTournaments/index.tsx
> +                    );
I casted its type from any to any[] via Array.from while having an index to add as a key to the li component. This removes the console warnings when rendering an array of elements without keys

2024-05-30 05:46 UTC, idiglove approved these changes
All good, nice one

2024-05-30 05:47 UTC, merged