[AR-48] Update to above the fold and navigation menu (desktop + mobile)
idiglove/aintboard pull request #504
Opened 2024-07-07 13:30 UTC by aljersulit

2024-07-07 23:31 UTC, idiglove requested changes
I have some comments, pls address them. Will test the work now

2024-07-07 23:31 UTC, idiglove commented on components/Navbar/LoginButton/LoginButton.tsx
> +            $color="#bcbcbc"
if theres a new color pls add them to `styles/theme.ts`

2024-07-07 23:31 UTC, idiglove commented on components/Navbar/LoginButton/styled.ts
> +  // @media (max-width: ${(props) => props.theme.breakpoints.sm}) {
can we remove comments?

2024-07-07 23:31 UTC, idiglove commented on components/Navbar/index.tsx
> +// import TwitterIcon from "assets/img/TwitterIcon";
pls remove comments

2024-07-07 23:31 UTC, idiglove commented on components/Navbar/index.tsx
> +  // InformationContainerStyled,
remove comments

2024-07-07 23:31 UTC, idiglove commented on components/Navbar/index.tsx
> +                Cash Tournaments
we have these links now
about -> /about
discord -> https://discord.com/invite/fpvUHHc2XN
cash tournaments -> /boardgame-tournaments

2024-07-07 23:31 UTC, idiglove commented on components/Navbar/index.tsx
>                </InformationContainerStyled>
remove comments

2024-07-07 23:31 UTC, idiglove commented on components/Navbar/styled.ts
> +
remove comments pls

2024-07-07 23:31 UTC, idiglove commented on components/Navbar/styled.ts
> +//   .text-top {
remove comments

2024-07-07 23:34 UTC, idiglove commented
<img width="1505" alt="image" src="https://github.com/idiglove/aintboard/assets/29911508/875ebf85-c5fe-4fdf-8e12-17aaa67fff7b">
this should always be centered. the gap between them should be max 32px

2024-07-07 23:34 UTC, idiglove commented
And on that screenshot, not sure if I'm logged in or not. We should always show the hamburger menu
The logout is there if Im logged in

2024-07-08 06:54 UTC, aljersulit commented on components/Navbar/LoginButton/LoginButton.tsx
> +            $color="#bcbcbc"
Is there a way to access the theme in a regular component?

2024-07-08 07:39 UTC, aljersulit commented on components/Navbar/index.tsx
> +                Cash Tournaments
Should I store them in .env?

2024-07-09 02:46 UTC, Script-Sage28 reviewed
Kindly see comments @aljersulit

2024-07-09 02:46 UTC, Script-Sage28 commented on components/Navbar/index.tsx
> +                Cash Tournaments
> Should I store them in .env?

Yes @aljersulit and replace the value of href attribute to its designated link instead of '#'.

2024-07-09 02:46 UTC, Script-Sage28 commented on components/Navbar/LoginButton/LoginButton.tsx
> +            $color="#bcbcbc"
> Is there a way to access the theme in a regular component?

Yes @aljersulit just import the theme from `styles/theme.ts`  and you can access it.

2024-07-09 02:56 UTC, Script-Sage28 reviewed
Kindly see comments @aljersulit

2024-07-09 02:56 UTC, Script-Sage28 commented on components/Navbar/index.tsx
> +            {/* <h2 className="headingText">Bringing Boardgames to Life.</h2> */}
Remove commented/unused codes.

2024-07-09 03:09 UTC, Script-Sage28 commented on components/Navbar/LoginButton/LoginButton.tsx
> +            $color="#bcbcbc"
You can simply `useTheme `hook of styled-components to access a specific color.

Example:

```
import { useTheme } from 'styled-components';
const theme = useTheme();

<BtnStyled
            $color={theme.colors.new_color}
            $border={true}
            onClick={() => {
              signIn();
            }}
          >
            <p>Join</p>
 </BtnStyled>
```
 
` new_color` will be represent the name of your newly added color in `styles/theme.ts`

2024-07-09 03:57 UTC, idiglove reviewed
some comments, im gonna test it now

2024-07-09 03:57 UTC, idiglove commented on components/Navbar/LoginButton/LoginButton.tsx
> +  console.log(theme);
remove console logs pls

2024-07-09 03:57 UTC, idiglove commented on components/Navbar/index.tsx
> +              <Link href="#">
contact link should be /contact

2024-07-09 03:58 UTC, idiglove commented
Your signup link should go to /signup

2024-07-09 04:00 UTC, idiglove commented
<img width="244" alt="image" src="https://github.com/idiglove/aintboard/assets/29911508/6f4ac710-ca65-4642-af72-c754bbdeacd5">
Pls also implement mobile and tablet to look like this, thanks!

2024-07-09 14:06 UTC, Script-Sage28 requested changes
Hi @aljersulit kindly see my minor comments

2024-07-09 14:06 UTC, Script-Sage28 commented on components/Navbar/LoginButton/LoginButton.tsx
> +  console.log(theme);
- Remove console logs @aljersulit

2024-07-09 14:06 UTC, Script-Sage28 commented on components/Navbar/LoginButton/LoginButton.tsx
> +  console.log("Hello World");
- Remove console logs @aljersulit

2024-07-09 14:06 UTC, Script-Sage28 commented on components/Navbar/index.tsx
- Please remove this ` {/* {userObj && status === AUTH_STATUS.authenticated ? ( */}` in line 143 if it's unused.

2024-07-09 14:06 UTC, Script-Sage28 commented on components/Navbar/styled.ts
>      color: #ffffff;
- Use the declared white color in `styles/theme.ts`

2024-07-10 03:06 UTC, idiglove approved these changes
Good job @aljersulit !! And thanks for the PR reviews @Script-Sage28 
Merging now

2024-07-10 03:06 UTC, merged