[AT-77] FE: Updates images should be clickable and viewed in a modal
idiglove/aintboard pull request #505
Opened 2024-07-08 12:48 UTC by wagbubu

Additional: Fix Footer
Footer is actually confusing to fix as well, There are 2 pages that uses different footer  but same component (copy and pasted) the homapage and the boardgame-tournaments, while the homepage is at pages router and uses styled components. I discovered that the footer at boardgame-tournaments/ is still using the "styled component" even if its at app router already.. and it's even more confusing because it's using the same names so when I ctrl + click sometimes it redirects to the pages router and sometimes to the app router, that's why I don't see my changes being applied.

this is now fixed, maybe we can convert this footer at app router to TW next time?

edit:I don't know if it's right but I can delete my fix (i think) for footer if the footer is intended that way..

THANKS!

2024-07-09 02:45 UTC, Script-Sage28 reviewed
Kindly see my comments :)

2024-07-09 02:45 UTC, Script-Sage28 commented on app/_components/Footer/styled.ts
>    color: #bcbcbc;
Put this color in `styles/theme.ts`

2024-07-09 02:45 UTC, Script-Sage28 commented on app/_components/Footer/styled.ts
>    color: #bcbcbc;
Put this color in `styles/theme.ts`

2024-07-09 02:45 UTC, Script-Sage28 commented on app/boardgame-tournaments/[gameTitleSlug]/_components/Updates/Modal.tsx
> +      background: "#1f3838",
Put this color in `styles/theme.ts`

2024-07-09 02:53 UTC, idiglove requested changes
some comments

2024-07-09 02:53 UTC, idiglove commented on app/_components/Footer/styled.ts
>    color: #bcbcbc;
it's ok we can leave it for now, this PR shouldnt even touch Footer, and I dunno why we have to do it @wagbubu

2024-07-09 02:53 UTC, idiglove commented on app/boardgame-tournaments/[gameTitleSlug]/_components/Updates/Modal.tsx
> +      shouldCloseOnEsc={true}
```suggestion
      shouldCloseOnOverlayClick
      shouldCloseOnEsc
```

no need to explicitly say ={true}

2024-07-09 02:53 UTC, idiglove commented on components/Navbar/DropDown/styled.ts
> -  z-index: ${(props) => props.theme.zIndex["6th"]};
hmm why?

2024-07-09 02:53 UTC, idiglove commented on components/Navbar/DropDown/styled.ts
> -  z-index: ${(props) => props.theme.zIndex["6th"]};
we might be regressing something here

2024-07-09 02:56 UTC, idiglove commented
UI looks good! Just left some comments :)

2024-07-09 03:31 UTC, wagbubu commented on app/_components/Footer/styled.ts
>    color: #bcbcbc;
uhm.. it's a minor fix at the footer, it's making the drawer on the side show a little
so I adjusted it..

I just changed it so it'll be easier to change something/develop on local and see your actual changes in CSS
![image](https://github.com/idiglove/aintboard/assets/150876994/5b2f99f9-c156-430c-bb2a-c020baea71d5)
![image](https://github.com/idiglove/aintboard/assets/150876994/ff9e453d-5a97-48bd-8ab9-1291d216f1cb)

2024-07-09 03:35 UTC, wagbubu commented on app/_components/Footer/styled.ts
>    color: #bcbcbc;
I just read your comments below, I will reset this commit, thanks!

2024-07-09 03:36 UTC, wagbubu commented on app/boardgame-tournaments/[gameTitleSlug]/_components/Updates/Modal.tsx
> +      shouldCloseOnEsc={true}
oooh... got it. what is this technique called?

2024-07-09 03:39 UTC, wagbubu commented on components/Navbar/DropDown/styled.ts
> -  z-index: ${(props) => props.theme.zIndex["6th"]};
my first thought is this was inheriting the parent's z index and works fine without it, when you add this all drop down button was on top.. but I'm gonna double check maybe this has changed because I'm now using react-modal

2024-07-09 03:54 UTC, idiglove commented on components/Navbar/DropDown/styled.ts
> -  z-index: ${(props) => props.theme.zIndex["6th"]};
yea cos i remember i had a problem with modals with dropdowns. Since your Image Viewer doesnt have dropdown, it would be fine to retain this z-index

2024-07-09 03:54 UTC, idiglove commented on app/boardgame-tournaments/[gameTitleSlug]/_components/Updates/Modal.tsx
> +      shouldCloseOnEsc={true}
not sure haha, since it's not undefined, it results to true :))

2024-07-09 03:55 UTC, idiglove commented on app/_components/Footer/styled.ts
>    color: #bcbcbc;
ok cools, thanks for the explanation

2024-07-09 07:29 UTC, wagbubu commented on app/boardgame-tournaments/[gameTitleSlug]/_components/Updates/Modal.tsx
> +      background: "#1f3838",
I got this from color picker.. I think the color is the theme but different hex(same color/almost) but it's the one being used as "green"  components as well so I'll just use that.

2024-07-09 07:38 UTC, wagbubu commented on app/boardgame-tournaments/[gameTitleSlug]/_components/Updates/Modal.tsx
> +      background: "#1f3838",
hmm.. it's slightly different. I'll do what you said, I'm just gonna add this. thanks..

2024-07-09 07:45 UTC, wagbubu commented on components/Navbar/DropDown/styled.ts
> -  z-index: ${(props) => props.theme.zIndex["6th"]};
confirmed: it's working even with z-index = 6th, I'm gonna revert this back, i think i was just confused troubleshooting and forgot to bring back my other changes that did not work.. my  bad.

Thanks!

2024-07-09 13:56 UTC, Script-Sage28 approved these changes
This is approved!. Great job @wagbubu

2024-07-10 03:03 UTC, idiglove reviewed
i have more comments, sorry about that! :D

2024-07-10 03:03 UTC, idiglove commented on app/boardgame-tournaments/[gameTitleSlug]/_components/Updates/ImageViewer.tsx
> +import Xbutton from "app/boardgame-tournaments/[gameTitleSlug]/_components/Updates/Xbutton";
can we move the buttons to /assets folder instead?

2024-07-10 03:03 UTC, idiglove commented on app/boardgame-tournaments/[gameTitleSlug]/_components/Updates/Modal.tsx
> +import Modal from "react-modal";
this is a very common file that doesnt really relate to tournaments only. we can move it to a more generic folder

2024-07-10 03:03 UTC, idiglove commented on app/boardgame-tournaments/[gameTitleSlug]/_components/Updates/index.tsx
> +                <ImageViewer imageUrl={item.image.node.sourceUrl} />
since item is from backend, and backend might fail or be delayed lets add more null checking guards:
item?.image?.node?.sourceUrl

2024-07-10 07:20 UTC, wagbubu commented on app/boardgame-tournaments/[gameTitleSlug]/_components/Updates/Modal.tsx
> +import Modal from "react-modal";
I will move it in the root  _components folder

2024-07-10 07:24 UTC, wagbubu commented on app/boardgame-tournaments/[gameTitleSlug]/_components/Updates/ImageViewer.tsx
> +import Xbutton from "app/boardgame-tournaments/[gameTitleSlug]/_components/Updates/Xbutton";
moved to @/assets/

2024-07-10 07:24 UTC, wagbubu commented on app/boardgame-tournaments/[gameTitleSlug]/_components/Updates/Modal.tsx
> +import Modal from "react-modal";
moved to @/app/_components/

2024-07-10 07:25 UTC, wagbubu commented on app/boardgame-tournaments/[gameTitleSlug]/_components/Updates/index.tsx
> +                <ImageViewer imageUrl={item.image.node.sourceUrl} />
Oh yyuppp! I forgot.. my bad 😅

2024-07-10 13:14 UTC, Script-Sage28 approved these changes
Check my minor comment @wagbubu

2024-07-10 13:23 UTC, Script-Sage28 requested changes
Left minor comments

2024-07-10 13:23 UTC, Script-Sage28 commented on app/boardgame-tournaments/[gameTitleSlug]/_components/Updates/index.tsx
> +                <ImageViewer imageUrl={item?.image?.node?.sourceUrl} />
- Can we add a link to an image to serve as a placeholder if this item might be an empty string `item?.image?.node?.sourceUrl`?" if you can consider that. @wagbubu 

example: 
 `<ImageViewer imageUrl={item?.image?.node?.sourceUrl || 'image_placeholder_link'} />`

2024-07-11 06:13 UTC, wagbubu commented on app/boardgame-tournaments/[gameTitleSlug]/_components/Updates/index.tsx
> +                <ImageViewer imageUrl={item?.image?.node?.sourceUrl} />
Done! took me time, there was an error in tailwind. the X in the button was missing but I did not change anything.

I just tried to detach the head copy the whole X button and attached it back and paste then it worked -_- weird. I might have erased something accidentally that I can't even find.

2024-07-11 06:45 UTC, wagbubu commented on app/boardgame-tournaments/[gameTitleSlug]/_components/Updates/index.tsx
> +                <ImageViewer imageUrl={item?.image?.node?.sourceUrl} />
All done, turns out it was cache, so I did not fix anything. I figured out that if my Xbutton component doesnt work if it's in the assets/.. I moved it to the root folder app/_components/ instead.. and it worked again.

2024-07-11 06:46 UTC, idiglove approved these changes
Good job and thanks for being patient with our PR reviews :)))
🏄🏽 keep it up!

2024-07-11 06:46 UTC, idiglove commented
@wagbubu Feel free to merge when Vercel deploy build is fine

2024-07-11 06:59 UTC, merged