[AMP-64] Migrate User Settings page to App Router
idiglove/aintboard pull request #506
Opened 2024-07-09 08:15 UTC by enzoperce35

2024-07-09 13:53 UTC, Script-Sage28 requested changes
Hi @enzoperce35 kindly see my comments.

2024-07-09 13:53 UTC, Script-Sage28 commented on components/SettingsPage/index.tsx
> +      if (images.length) {
- I think we can put the logic in line 34 inside of this since you are checking the length of images?

2024-07-09 13:53 UTC, Script-Sage28 commented on components/SettingsPage/index.tsx
> +    <div className="relative min-h-[calc(100vh - 40rem)] -mt-4 bg-[#234C4C] z-[7]">
- Can you put the color of `#234C4C` inside `styles/theme.ts` if it's new.

2024-07-09 13:53 UTC, Script-Sage28 commented on components/SettingsPage/index.tsx
> +                  <div className="flex justify-start text-[#E15A5A] mb-2 text-[0.8rem]">
- Can you put the color of `#E15A5A` inside `styles/theme.ts` if it's new.

2024-07-09 13:53 UTC, Script-Sage28 commented on components/SettingsPage/index.tsx
> +                  <div className="flex justify-start text-[#E15A5A] mb-2 text-[0.8rem]">
- Can you put the color of `#E15A5A` inside `styles/theme.ts` if it's new.

2024-07-09 13:53 UTC, Script-Sage28 commented on components/SettingsPage/index.tsx
> +      console.error("Settings update error: ", err);
- Remove logs from console

2024-07-09 14:01 UTC, enzoperce35 commented on components/SettingsPage/index.tsx
> +      if (images.length) {
ok sir will do

2024-07-09 14:06 UTC, enzoperce35 commented on components/SettingsPage/index.tsx
> +      console.error("Settings update error: ", err);
ok sir, will remove logs

2024-07-09 14:45 UTC, enzoperce35 commented on components/SettingsPage/index.tsx
> +    <div className="relative min-h-[calc(100vh - 40rem)] -mt-4 bg-[#234C4C] z-[7]">
this color is already inside styles/theme.ts sir, it is named darkGreen.

2024-07-09 14:46 UTC, enzoperce35 commented on components/SettingsPage/index.tsx
> +                  <div className="flex justify-start text-[#E15A5A] mb-2 text-[0.8rem]">
this color is already inside styles/theme.ts sir, it is named errorRed.

2024-07-09 14:46 UTC, enzoperce35 commented on components/SettingsPage/index.tsx
> +                  <div className="flex justify-start text-[#E15A5A] mb-2 text-[0.8rem]">
this color is already inside styles/theme.ts sir, it is named errorRed.

2024-07-09 14:57 UTC, Script-Sage28 commented on components/SettingsPage/index.tsx
> +    <div className="relative min-h-[calc(100vh - 40rem)] -mt-4 bg-[#234C4C] z-[7]">
If that's so, you can use the `useTheme `hook from `styled-components` to access the darkGreen color from the theme.

Example:
```
import {  useTheme } from 'styled-components'
const theme = useTheme()

<div className=`relative min-h-[calc(100vh - 40rem)] -mt-4 bg-[${theme.colors.darkGreen}] z-[7]`></div>
```

2024-07-09 14:57 UTC, Script-Sage28 commented on components/SettingsPage/index.tsx
> +                  <div className="flex justify-start text-[#E15A5A] mb-2 text-[0.8rem]">
- Use `useTheme `hook from `styled-components` to access it.

2024-07-09 14:57 UTC, Script-Sage28 commented on components/SettingsPage/index.tsx
> +                  <div className="flex justify-start text-[#E15A5A] mb-2 text-[0.8rem]">
- Use `useTheme `hook from `styled-components` to access it.

2024-07-09 15:06 UTC, enzoperce35 commented on components/SettingsPage/index.tsx
> +    <div className="relative min-h-[calc(100vh - 40rem)] -mt-4 bg-[#234C4C] z-[7]">
Ok sir, thanks for letting me know it's possible

2024-07-09 15:50 UTC, enzoperce35 commented on components/SettingsPage/index.tsx
> +    <div className="relative min-h-[calc(100vh - 40rem)] -mt-4 bg-[#234C4C] z-[7]">
![Screen Shot 2024-07-09 at 11 49 15 PM](https://github.com/idiglove/aintboard/assets/61140261/9fa2751e-fdc6-4483-9ffd-9f3f7842c59b)
![Screen Shot 2024-07-09 at 11 49 46 PM](https://github.com/idiglove/aintboard/assets/61140261/8a0adc7b-44d1-4d4f-829e-43e5906dd803)

2024-07-09 15:51 UTC, enzoperce35 commented on components/SettingsPage/index.tsx
> +    <div className="relative min-h-[calc(100vh - 40rem)] -mt-4 bg-[#234C4C] z-[7]">
sir it's not working for me, am i missing something?

2024-07-09 16:08 UTC, enzoperce35 commented on components/SettingsPage/index.tsx
> +    <div className="relative min-h-[calc(100vh - 40rem)] -mt-4 bg-[#234C4C] z-[7]">
it's now solved sir, thank you

2024-07-10 03:09 UTC, idiglove requested changes
awesome job so far, just few comments and need u to collab with Jelo

2024-07-10 03:09 UTC, idiglove commented on components/SettingsPage/index.tsx
> +  const onSubmit = async (values: any, actions: any) => {
can we improve typescript for the props? It's a bit hard so may need help from @Script-Sage28

2024-07-10 03:09 UTC, idiglove commented on components/SettingsPage/index.tsx
> +      <main className="w-4/5 mx-[auto] my-[0] p-20 text-[white]">
why not text-white?

2024-07-10 03:09 UTC, idiglove commented on components/SettingsPage/index.tsx
> +                  <div className="relative w-[30rem] h-[30rem] mt-4 mb-4">
👍🏽

2024-07-10 03:19 UTC, enzoperce35 commented on components/SettingsPage/index.tsx
> +  const onSubmit = async (values: any, actions: any) => {
Ok maam, will reach out @Script-Sage28 for this

2024-07-10 03:21 UTC, enzoperce35 commented on components/SettingsPage/index.tsx
> +      <main className="w-4/5 mx-[auto] my-[0] p-20 text-[white]">
missed this one from my last commit

2024-07-11 02:25 UTC, idiglove approved these changes
Looks good so far! Although i see few bugs in this page. I will assign to you the ticket. 💯

2024-07-11 02:25 UTC, merged