[AMP-66] Fix User Settings Page
idiglove/aintboard pull request #510
Opened 2024-07-13 08:14 UTC by enzoperce35

2024-07-15 01:32 UTC, idiglove requested changes
I have some comments :)

2024-07-15 01:32 UTC, idiglove commented on app/user/[username]/settings/page.tsx
> +        {userName === null ? userObj?.username : userName} Settings
the correct way is to refetch auth session. Not sure how to do it, but userObj should be updated after changing the username. Can you research how to do it? Thanks

2024-07-15 01:32 UTC, idiglove commented on components/Common/Sidebar/index.tsx
> +                link={`/user/${userObj?.username ?? userObj?.name}/settings`}
name's have spaces, did you consider this?

2024-07-15 01:32 UTC, idiglove commented on components/Common/Sidebar/index.tsx
> +                link={`/user/${userObj?.username ?? userObj?.name}/settings`}
you should slugify this

2024-07-15 01:32 UTC, idiglove commented on components/SettingsPage/index.tsx
> +const SettingsPage = (props: Props) => {
why did we remove destructure?

2024-07-15 04:20 UTC, Script-Sage28 requested changes

2024-07-15 04:20 UTC, Script-Sage28 commented on app/user/[username]/settings/page.tsx
> +        {userName === null ? userObj?.username : userName} Settings
In addition, you can simplify the condition by doing this `userObj?.username ?? userName`

2024-07-15 04:25 UTC, enzoperce35 commented on app/user/[username]/settings/page.tsx
> +        {userName === null ? userObj?.username : userName} Settings
thank you for the reviews, will revise the issues ☺️

2024-07-15 04:30 UTC, enzoperce35 commented on components/Common/Sidebar/index.tsx
> +                link={`/user/${userObj?.username ?? userObj?.name}/settings`}
will do maam, i'll check it out

2024-07-15 04:34 UTC, enzoperce35 commented on components/SettingsPage/index.tsx
> +const SettingsPage = (props: Props) => {
i think that's just what i came up with for trying to use a functional component as a prop, but i think it will be modified as i'll change my approach to auth session re-fetch

2024-07-19 01:51 UTC, idiglove approved these changes
bravo! ⭐

2024-07-19 01:52 UTC, merged